### ISSUE TITLE
Unexpected behavior when adding course

### ISSUE THREAD

**Issue by LukasAbraham** [maqnitude/uit-planner#18]
After filling out and submitting the course form, the courses screen displays 2 duplicated courses.
<img width="281" alt="image" src="https://github.com/maqnitude/uit-planner/assets/94582919/823efd1e-b2fe-422c-830e-ee1978f44801">
<img width="284" alt="image" src="https://github.com/maqnitude/uit-planner/assets/94582919/fbfa8c8b-64f9-4136-aee4-ee76eec2b533">
However, if I reload the screen, it displays correctly.
<img width="285" alt="image" src="https://github.com/maqnitude/uit-planner/assets/94582919/9812c605-68d2-4a2a-bb0e-5c4d1741a315">

**Comment by maqnitude** [comment]
Could not replicate this behavior on my machine.
